/* RHEL 10 Interview Questions — 50 Q&A across all topics */
window.RHEL10_QA = [
  {t:"Boot & GRUB", q:"How do you recover a forgotten root password on RHEL 10?",
   a:"Reboot, at the GRUB menu press 'e' to edit, append rd.break to the kernel (linux) line, Ctrl-X to boot. You land in a switch_root emergency shell. Remount the sysroot read-write with mount -o remount,rw /sysroot, chroot /sysroot, run passwd root (and touch /.autorelabel if SELinux is enforcing), then exit twice to continue booting.",
   e:"rd.break interrupts before the root filesystem is mounted read-write. Remounting rw lets you change the root filesystem; chroot switches into the real system. touch /.autorelabel ensures SELinux labels are fixed after editing /etc/shadow outside policy."},
  {t:"Boot & GRUB", q:"What is the difference between BIOS/MBR and UEFI/GPT boot on RHEL 10?",
   a:"BIOS boots from the MBR and loads GRUB stage1 from the first 512 bytes, limited to 2 TB disks and 4 primary partitions. UEFI uses a FAT-formatted EFI System Partition (ESP, /boot/efi), loads GRUB as an EFI application (shim.efi/grubx64.efi), supports GPT (large disks, many partitions) and Secure Boot.",
   e:"On Secure Boot systems RHEL loads shim (signed by Microsoft), which then loads the Red Hat-signed GRUB and kernel. GPT is used with UEFI; MBR traditionally with legacy BIOS."},
  {t:"Boot & GRUB", q:"How do you change the default boot kernel or kernel command-line parameters persistently?",
   a:"Use grubby: grubby --set-default /boot/vmlinuz-<version> sets the default kernel. Persistent kernel arguments are managed with grubby --update-kernel=ALL --args=\"<params>\" (or --remove-args). grubby --default-kernel and --info show the running/default entries.",
   e:"RHEL also supports KernelCare/kpatch for live patching. grubby edits BLS (BootLoaderSpec) snippets in /boot/loader/entries; you should not hand-edit grub.cfg on modern RHEL."},
  {t:"Boot & GRUB", q:"The boot drops into an emergency or rescue target. What is the difference and how do you proceed?",
   a:"emergency.target is the most minimal — it mounts only the root filesystem read-only and starts almost nothing (like single-user). rescue.target is slightly fuller, mounting local filesystems and starting basic services. Log in as root, fix the issue (often /etc/fstab errors), then systemctl reboot (or daemon-reload).",
   e:"Common causes are a bad /etc/fstab entry, missing device, or corrupted root mount. emergency.target gives a shell when even rescue cannot mount filesystems."},

  {t:"Packages & Software", q:"What package manager does RHEL 10 use and what are the key commands?",
   a:"dnf is the front end to RPM (rpm-ostree aside). Install: dnf install pkg; remove: dnf remove; update: dnf upgrade; search: dnf search; info: dnf info; list: dnf list installed/available; history rollback: dnf history undo <id>. rpm -qa lists installed RPMs; rpm -ql/-qf inspect file ownership.",
   e:"DNF replaced yum and provides better dependency resolution (libsolv) and transaction history. AppStreams (modular repos in RHEL 8) are simplified in RHEL 9/10 with regular repos."},
  {t:"Packages & Software", q:"How does dnf history help recover from a bad update?",
   a:"dnf history lists transactions with IDs; dnf history info <id> shows details; dnf history undo <id> reverses an operation and dnf history rollback <id> downgrades/upgrades to the package set that existed at that transaction.",
   e:"This requires the needed packages to still be available in configured repos. It is the fastest supported way to revert a broken upgrade set."},
  {t:"Packages & Software", q:"A repository is not enabled or a system is offline — how do you install a package from an RPM file?",
   a:"dnf localinstall ./package.rpm (or just dnf install ./package.rpm) installs it and pulls dependencies from configured repos. With no network, rpm -ivh package.rpm installs but does not resolve dependencies automatically.",
   e:"Always verify packages with rpm -K or the Red Hat signature; dnf resolves deps whereas raw rpm does not."},

  {t:"systemd", q:"How do you enable, start, and create a systemd service?",
   a:"systemctl start/stop/restart/reload unit; systemctl enable --now unit both enables and starts. Status: systemctl status unit. To create one, drop a .service file in /etc/systemd/system/ with [Unit], [Service] (ExecStart etc.), and [Install] WantedBy=multi-user.target, then systemctl daemon-reload and enable.",
   e:"/etc/systemd/system is for admin overrides and is higher priority than /usr/lib/systemd/system. daemon-reload picks up new/changed unit files before restarting."},
  {t:"systemd", q:"A service fails on boot. How do you troubleshoot it?",
   a:"systemctl status unit and journalctl -u unit (-b for current boot, -xe for context) show the failure; systemctl cat unit shows the resolved unit; run the ExecStart command manually to see errors. Check After=/Requires= ordering and dependencies. Restart after fixes with daemon-reload && restart.",
   e:"Common causes: wrong path/command, permissions, missing environment file, or a required service/network not yet up. systemd-analyze blame/verify can help with ordering and unit issues."},
  {t:"systemd", q:"Explain targets in systemd and the relationship to old runlevels.",
   a:"Targets are synchronization points that group units (like runlevels but dependency-based). multi-user.target is non-graphical multi-user (≈ runlevel 3); graphical.target is graphical (≈ runlevel 5); rescue.target ≈ 1, emergency.target ≈ single. Set default with systemctl set-default target.",
   e:"Runlevel compatibility aliases exist (runlevel3.target → multi-user.target). systemctl isolate target switches targets at runtime."},

  {t:"Users & Permissions", q:"How do you create a user, set a password, and grant sudo on RHEL 10?",
   a:"useradd alice creates the account (defaults from /etc/login.defs and /etc/default/useradd); passwd alice sets the password. Grant sudo by adding to the wheel group: usermod -aG wheel alice (wheel has %wheel ALL=(ALL) ALL in /etc/sudoers). Prefer visudo to edit /etc/sudoers safely.",
   e:"useradd -m ensures a home directory (default on RHEL). wheel is the standard admin group; visudo syntax-checks to avoid locking out sudo."},
  {t:"Users & Permissions", q:"Explain chmod numeric (octal) permissions and setuid.",
   a:"Three digits for owner/group/other, each 4=read,2=write,1=execute: 755 = rwxr-xr-x, 644 = rw-r--r--. setuid (chmod 4xxx) runs an executable as its owner (e.g., passwd runs as root to write /etc/shadow); setgid (2xxx) runs with the file's group; sticky bit (1xxx, as on /tmp) lets only a file's owner delete it.",
   e:"Example: passwd is setuid root so ordinary users can change their password safely. The symbolic equivalent for setuid is chmod u+s. Avoid setuid shell scripts for security."},
  {t:"Users & Permissions", q:"What does umask control and what is the RHEL 10 default?",
   a:"umask sets the default permissions mask for newly created files/directories: a file defaults to 666, directory 777, minus the umask. The default user umask is 022 (files 644, dirs 755); many systems use 077 for more privacy (files 600, dirs 700). Check with umask.",
   e:"DefaultUserTasks/umask can be set in /etc/profile.d or /etc/bashrc; systemd sets UserTasksMax etc. separately."},

  {t:"Storage & LVM", q:"What are LVM physical volumes, volume groups and logical volumes?",
   a:"PV: disk/partition initialized with pvcreate. VG: pool of PVs (vgcreate). LV: logical volumes cut from the VG (lvcreate) that host filesystems. Layers: PV → VG → LV → filesystem (e.g. /dev/vgname/lvname → mkfs.xfs → mount).",
   e:"LVM enables online resize (lvextend/xfs_growfs or resize2fs), snapshots (lvcreate -s), and moving data (pvmove) across disks without downtime."},
  {t:"Storage & LVM", q:"How do you extend an XFS filesystem on an LVM logical volume?",
   a:"Add a disk/partition, pvcreate it, vgextend <vg> <pv>, lvextend -L +<size> /dev/<vg>/<lv> (or -r to resize the FS automatically), then xfs_growfs <mountpoint> (XFS can only grow). Verify with vgs/lvs and df -h.",
   e:"ext4 uses resize2fs instead and can shrink offline; XFS grows only online. lvextend -r runs the correct fs resize automatically."},
  {t:"Storage & LVM", q:"How do you create a persistent mount in /etc/fstab, and what fields matter?",
   a:"Add a line: <device/UUID> <mountpoint> <fstype> <options> <dump> <pass>. Use UUID=... (from blkid) for stability, fstype xfs/ext4, options defaults, dump 0, pass 0 (or 1 for root). Run systemctl daemon-reload and mount -a to test (must succeed or boot may drop to emergency).",
   e:"mount -a mounts everything in fstab and will error on a bad entry — always test before rebooting. x-systemd.requires/automount are advanced options."},

  {t:"SELinux", q:"What is SELinux and how does RHEL 10 use it by default?",
   a:"SELinux is a Mandatory Access Control (MAC) system enforcing type enforcement on processes (domains) and files (types). RHEL runs it in enforcing mode with the targeted policy by default. Check with getenforce/sestatus; toggle with setenforce 0|1 (temporary); persistent mode in /etc/selinux/config.",
   e:"MAC complements discretionary DAC (u/g/o). Setting setenforce 0 masks problems and is not a fix — the correct approach is booleans/contexts/policy."},
  {t:"SELinux", q:"A web page shows permission denied but standard DAC looks fine. What do you check?",
   a:"Likely SELinux: ls -Z shows the file context, ps -Z the process domain. AVC denials appear in /var/log/audit/audit.log (ausearch -m avc). Fixes: restorecon -Rv /path sets the default context; semanage fcontext -a -t httpd_sys_content_t '/path(/.*)?' then restorecon for persistent custom paths; setsebool -P httpd_read_user_content on to enable a boolean.",
   e:"Moving files into a web root (cp/mv) often carries the wrong context (e.g. user_home_t). restorecon reapplies the correct labeled type; booleans toggle policy behavior without disabling SELinux."},
  {t:"SELinux", q:"Explain SELinux context, mode, and what a relabel does.",
   a:"Every object has a context (user:role:type:level); type enforcement controls access between domains and types. Modes are enforcing (deny+log), permissive (log only), disabled (off). A full relabel with touch /.autorelabel (reboot) or fixfiles/restorecon restores default labels after they have been corrupted or after a policy/relabel issue.",
   e:"relabel is used after changing files outside policy (e.g. root password recovery, copying a filesystem). restorecon is the targeted, non-disruptive equivalent."},

  {t:"Networking", q:"What replaces NetworkManager/nmcli configuration of interfaces?",
   a:"NetworkManager via nmcli/nmtui is standard. nmcli con show lists connections; nmcli con mod \"System ens192\" ipv4.addresses 192.168.1.10/24 ipv4.gateway 192.168.1.1 ipv4.dns 8.8.8.8 ipv4.method manual then nmcli con up \"System ens192\" activates it. Changes persist in /etc/NetworkManager/system-connections/ (keyfile) or legacy ifcfg.",
   e:"RHEL 9/10 uses keyfiles by default (ifcfg is deprecated). nmcli is the supported, scriptable CLI; nmtui provides a text UI."},
  {t:"Networking", q:"How do you test connectivity and view listening services on RHEL 10?",
   a:"ping/ip route (routing), ss -tulpn (listening TCP/UDP sockets and processes; replaces netstat), curl/-I or wget for HTTP, dig/host (bind-utils) for DNS resolution, nmcli con show / ip addr show. firewalld status with firewall-cmd --list-all.",
   e:"ss is faster than netstat and shows socket state; -t tcp, -u udp, -l listening, -p process, -n numeric."},
  {t:"Networking", q:"How does firewalld work and how do you open a service/port?",
   a:"firewalld manages zones (public by default). firewall-cmd --add-service=http (runtime), with --permanent to persist (then firewall-cmd --reload). A port: firewall-cmd --permanent --add-port=8080/tcp. List with --list-all. Zones (public, internal, trusted) apply to source/interface.",
   e:"Non-permanent changes are lost on reload/reboot — always add --permanent and reload. firewalld uses nftables backend under the hood on modern RHEL."},

  {t:"Processes & Performance", q:"How do you find and kill a runaway process on RHEL 10?",
   a:"ps aux | grep <name> or pgrep -a <name>; pidof <name>. Inspect with top/htop (P by CPU, M by memory), kill -TERM <pid> (15, graceful) first, kill -9 <pid> (SIGKILL, cannot be caught) if needed; pkill -f <pattern> by name. nice/renice and kill -STOP/-CONT pause/resume.",
   e:"Always try SIGTERM so the process can clean up; SIGKILL leaves files/locks in a bad state. systemctl stop is preferred for services."},
  {t:"Processes & Performance", q:"Explain load average and how to tell if a system is CPU-bound.",
   a:"uptime's load average is the number of runnable (R) plus uninterruptible-sleep (D, I/O) threads averaged over 1/5/15 minutes. Compare to CPU count (nproc). Sustainably above the core count = saturated. top/mpstat/pidstat show %CPU/%iowait/sy; high iowait with low us usually points to storage rather than CPU.",
   e:"Load alone is ambiguous on modern many-core systems — divide by nproc context. vmstat's 'r' column and 'wa' (iowait) are the classic drill-downs."},

  {t:"Log Management", q:"How do you read logs on RHEL 10?",
   a:"journald is the core: journalctl (-u unit, -b current boot, -f follow, -xe, --since/--until, -p err). Persistent journal storage is enabled by /var/log/journal (preset or mkdir + systemd-journald restart). Traditional /var/log/messages still exists (rsyslog). tail -f for live files.",
   e:"journalctl -u httpd -b narrows to a service this boot; persistent journals survive reboot whereas runtime storage is in /run/log/journal."},
  {t:"Log Management", q:"rsyslog vs journald — what is the difference?",
   a:"journald (systemd) is a structured binary journal collecting from all units with metadata (unit, priority), queried via journalctl. rsyslogd is the classic syslog daemon writing text files under /var/log and forwarding remotely per /etc/rsyslog.conf. They integrate: rsyslog pulls from the systemd journal via imjournal.",
   e:"On RHEL both run; journald provides rich filtering and rsyslog provides the legacy text logs and network forwarding."},

  {t:"Cron & Scheduling", q:"How do you schedule a recurring task and a one-shot future task?",
   a:"Recurring: crontab -e for a user, in /etc/crontab or drop-ins under /etc/cron.d/ with fields minute hour day month dow command. One-shot/relative: systemd timers are the modern approach (at is legacy). Check cron: systemctl status crond; list: crontab -l.",
   e:"systemd timer units (.timer + matching .service) give journaling and replace many at/cron uses; anacron handles missed jobs on laptops."},
  {t:"Cron & Scheduling", q:"A cron job does not run — what do you check?",
   a:"Check the user's crontab syntax and that the command uses absolute paths/PATH (cron has a minimal PATH), redirect output (output is emailed or lost), check /var/log/cron and journalctl -u crond, ensure crond is enabled/running, and that the file in /etc/cron.d is owned by root, named without extensions/periods and has correct SELinux context.",
   e:"% characters are special in crontab (newline) unless escaped \\%; run the job command manually from the shell with cron's minimal PATH to reproduce."},

  {t:"SSH & Security", q:"How do you configure key-based SSH authentication and harden sshd?",
   a:"Generate a key: ssh-keygen -t ed25519; copy it: ssh-copy-id user@host. Server hardening in /etc/ssh/sshd_config: PasswordAuthentication no, PermitRootLogin no, PubkeyAuthentication yes, then systemctl restart sshd. Verify with ssh -v. Use ssh-agent/ssh-add for keys.",
   e:"With PasswordAuthentication no and root login disabled, brute-force surface drops sharply. Keep your private key (~/.ssh/id_ed25519, mode 600) secret; the id_*.pub is distributed."},
  {t:"SSH & Security", q:"SSH fails with 'permission denied (publickey)'. What do you check?",
   a:"Client: correct private key (-i / -v), public key type support (ed25519/rsa). Server: user's ~/.ssh/authorized_keys contains the matching public key; permissions are strict (home 755 or stricter, ~/.ssh 700, authorized_keys 600) or StrictModes rejects login; SELinux context (restorecon -R ~/.ssh); sshd_config PubkeyAuthentication yes and AllowUsers/AllowGroups do not exclude the user; journalctl -u sshd shows the rejection.",
   e:"RHEL defaults to ssh_home_t labels; chmod/chown on .ssh often triggers StrictModes or SELinux denials. ssh -v (client) and journald (server) point to the exact stage failing."},

  {t:"Containers", q:"How are containers run and managed on RHEL 10?",
   a:"Podman is the supported daemonless, rootless container engine (Docker-compatible CLI): podman run -d --name web -p 8080:8080 httpd, podman ps, podman generate systemd / kube for persistent/systemd-managed workloads. Skopeo inspects/copies images; buildah builds. RHEL also supports CRI-O for Kubernetes.",
   e:"Podman runs rootless containers by default (better security) and uses systemd to manage lifecycle via podman generate systemd --new; there is no Docker daemon on RHEL."},

  {t:"Containers", q:"What is the difference between rootless and rootful containers?",
   a:"Rootless containers run the container as a regular unprivileged user mapping to a high-numbered UID inside the user namespace, so a container breakout cannot become host root. Rootful runs the runtime as root (more capabilities/port access, higher risk). Rootless may have limited access to <1024 ports (use 8080 or sysctl net.ipv4.ip_unprivileged_port_start) and some kernel features.",
   e:"RHEL/Podman default to rootless for safety; systemd integration (loginctl enable-linger) keeps rootless containers running after logout."},

  {t:"Backup", q:"What is the difference between tar, rsync, and restic for backups?",
   a:"tar archives (tar -czvf backup.tar.gz /etc) — simple, portable, full snapshots. rsync (rsync -aHAXv --delete src/ dest:/dir/) copies and syncs differences, preserves permissions, ideal for site-to-site and incremental-style mirroring. restic takes deduplicated, encrypted, incrementally versioned repositories (restic -r repo backup /path) with restic snapshots/restore.",
   e:"tar is a point-in-time archive; rsync mirrors with bandwidth efficiency (delta transfer); restic adds encryption, deduplication and easy point-in-time restore."},
  {t:"Backup", q:"How do you restore a specific file from an archive?",
   a:"tar: tar -tzf backup.tar.gz to list, tar -xzf backup.tar.gz -C /restore/path etc/app.conf to extract a file/path. rsync: run it in reverse from backup destination, or rsync backup:./file ./restore/. restic: restic -r repo restore latest --target /restore --include /etc/app.conf.",
   e:"Always extract to a staging directory rather than overwriting live configs, then diff/replace carefully."},

  {t:"Ansible", q:"What is Ansible and how does RHEL use it for automation?",
   a:"Ansible is an agentless automation tool that connects over SSH and executes YAML playbooks describing idempotent tasks, using an inventory of hosts and modules. RHEL is managed with the ansible-core package: ansible-playbook site.yml. Idempotence means running the playbook repeatedly leaves the system in the same desired state.",
   e:"No agent/daemon on managed nodes; Python on the target and SSH access are sufficient. RHEL System Roles (/usr/share/ansible/roles, linux-system-roles) provide supported config patterns (selinux, network, storage)."},
  {t:"Ansible", q:"What makes a task idempotent and why does it matter?",
   a:"An idempotent module only makes changes when the system differs from the desired state and reports 'ok'/'changed' vs failures. Re-running a playbook converges without error or duplicate side effects (e.g. yum/service/file modules check current state). Non-idempotent commands (shell/cmd) run every time unless guarded with when/changed_when/creates.",
   e:"Idempotence enables safe repeatable automation, predictability, and is required for rolling updates without side effects. Favor modules over raw commands."},

  {t:"Cockpit", q:"What is RHEL web console (Cockpit)?",
   a:"Cockpit is a browser-based (system management) UI on RHEL: install cockpit and enable/start the socket (systemctl enable --now cockpit.socket), connect at https://host:9090. It manages system, services, storage, networking, firewall, SELinux, updates, logs and podman containers; it executes real system commands and reflects state live.",
   e:"Cockpit is zero-state — it configures the same files/systemd/NetworkManager, so CLI and UI never conflict. Optional packages like cockpit-storaged/cockpit-podman add panels."},

  {t:"System Registration", q:"How is a RHEL 10 system registered for updates?",
   a:"Use subscription-manager (runs during Subscription Manager registration): subscription-manager register --username ... --password ..., auto-attach with subscription-manager attach --auto, then dnf repolist shows Red Hat repos (BaseOS/AppStream). Insights/insights-client provides predictive analytics.",
   e:"Insights (insights-client --register) uploads redacted metadata and gives remediation guidance. Unregistered systems only see base/no repo content."},
  {t:"System Registration", q:"How do you change which repositories are enabled on RHEL?",
   a:"subscription-manager repos --list shows all; --enable=rhel-10-for-x86_64-baseos-rpms (and appstream) / --disable=...; dnf repolist confirms; dnf config-manager --set-enabled can manage non-RH repos. A proxy is set in /etc/rhsm/rhsm.conf or yum.conf if needed.",
   e:"Codeready/eus repos follow similar naming; mixing RHEL minor release repos incorrectly causes dependency issues."},

  {t:"Performance Tuning", q:"What is tuned and how do profiles work?",
   a:"tuned is a system tuning daemon that applies kernel/system profiles for workloads. tuned-adm profile throughput-performance / virtual-guest / network-latency etc.; tuned-adm active shows current; tuned-adm recommend suggests. Profiles set sysctl, scheduler, power and disk settings dynamically.",
   e:"On VMs use virtual-guest; databases benefit from throughput-performance/network-throughput. tuned-adm profile list enumerates available profiles."},
  {t:"Performance Tuning", q:"Where are persistent kernel (sysctl) settings configured?",
   a:"Persist parameters in /etc/sysctl.conf or, preferred, a file in /etc/sysctl.d/<name>.conf (e.g. net.ipv4.ip_forward=1), then apply with sysctl --system; runtime test with sysctl -w key=value. Verify sysctl key and /usr/lib/sysctl.d for vendor defaults.",
   e:"RHEL 10/Tuned also sets values — /etc/sysctl.d plus tuned is the supported combination. Never hand-edit /proc/sys for persistence (they reset on boot)."},

  {t:"Storage Features", q:"What is Stratis and when would you use it?",
   a:"Stratis is a local storage-management layer on top of LVM/XFS that gives ZFS/Btrfs-like features simply: create a pool (stratis pool create) from block devices, then filesystems (stratis fs create); it provides snapshots, tiering (cache), thin provisioning and filesystem growth with the stratis-cli + stratisd service and a D-Bus API.",
   e:"Stratis filesystems are XFS and expand automatically; snapshots (stratis fs snapshot) are fast, space-efficient and used for rollback/testing — an alternative to manual LVM+XFS for easy management."},
  {t:"Storage Features", q:"What is VDO and how does it save storage?",
   a:"Virtual Data Optimizer provides deduplication, compression and thin provisioning on block storage to increase effective capacity. Created with vdo create --name=... --device=... --vdoLogicalSize=..., then mkfs.xfs on the /dev/mapper/vdo device and mount; monitor with vdostats.",
   e:"VDO deduplicates identical blocks (e.g. many VM images) and compresses data, ideal for KVM/object storage. Locate it under the filesystem; sizing uses logical vs physical."},

  {t:"SSH & Security", q:"How does SSH key generation differ with ed25519 vs RSA on RHEL 10?",
   a:"ssh-keygen -t ed25519 produces a modern, short, fast, Elliptic-curve key (recommended). RSA (-t rsa -b 4096) still works with stronger keys; OpenSSH in RHEL10 prefers/assumes stronger algorithms and may deprecate SHA-1 RSA. Both are placed in ~/.ssh/id_ed25519(.pub) / id_rsa(.pub).",
   e:"Ed25519 keys are small, offer equivalent/higher security at smaller key size and are preferred for new deployments; ssh-copy-id handles whichever public key is generated."},

  {t:"Boot Recovery", q:"How do you rebuild initramfs and a missing GRUB configuration?",
   a:"Rebuild the initramfs with dracut: dracut -f /boot/initramfs-$(uname -r).img $(uname -r) (or dracut --regenerate-all). Regenerate GRUB config with grub2-mkconfig -o /boot/grub2/grub.cfg (BIOS) or /boot/efi/EFI/redhat/grub.cfg (UEFI); use grub2-install on BIOS if the bootloader stage needs reinstall.",
   e:"Run dracut after adding kernel/storage drivers or when the initramfs is corrupt. On EFI you do not grub2-install a disk; grub2-mkconfig plus shim/ESP are used."},

  {t:"Troubleshooting", q:"A system reports 'No space left on device' but df shows free space. What do you investigate?",
   a:"Check inode exhaustion (df -i) — millions of small files use up inodes even with free bytes; deleted-but-open files (lsof | grep deleted or du after restart) where a process holds a file handle in /var; also check a full subdirectory mounted elsewhere hiding usage (du -x -h --max-depth=1 / | sort -h), and disk quota limits.",
   e:"df reports filesystem blocks; df -i reports inodes; a deleted log held open by a daemon still uses blocks until restart. du -x stays on one filesystem and finds real disk hogs."},
  {t:"Troubleshooting", q:"A service is slow and you suspect I/O. Which tools tell you?",
   a:"iostat -x 1 (high %util, await, r_await/w_await) shows device saturation and latency; vmstat 1 shows b (blocked processes) and wa (iowait); iotop/pidstat -d identifies the process; check dmesg/journal for disk errors and SAR (sar -d) historical trends.",
   e:"await is disk I/O latency (ms) — high await with high %util indicates a storage bottleneck; iowait is CPU idle waiting on disk and should be read with the other metrics."},

  {t:"Networking", q:"Which standard ports do common RHEL services use (ssh, http, https, dns, nfs, chrony)?",
   a:"ssh 22/tcp; HTTP 80/tcp; HTTPS 443/tcp; DNS 53 (udp/tcp); NFS 2049/tcp (rpcbind 111); NTP/chrony 123/udp (and 323/udp for chrony); SMTP 25; DHCP 67/68. Use ss -tulpn and /etc/services to confirm.",
   e:"These map directly to firewall-cmd services (ssh, http, https, dns, nfs). chrony uses UDP 123 to clients; NTS uses 4460."},

  {t:"Time & Chrony", q:"How do you configure time synchronization on RHEL 10?",
   a:"Chrony is default: configure servers/pools in /etc/chrony.conf (server time.example.com iburst), enable/start chronyd (systemctl enable --now chronyd), check with chronyc sources and chronyc tracking; timedatectl shows NTP service status; timedatectl set-timezone Asia/Kolkata sets zone.",
   e:"Chrony performs better than ntpd on VMs and intermittent networks. Ensure UDP 123 outbound; chronyc sources -v shows reachable stratum and offset."},
  {t:"Storage & LVM", q:"How do you add swap space on RHEL 10, both temporarily and persistently?",
   a:"Temporary: fallocate -l 2G /swapfile (or dd), chmod 600 /swapfile, mkswap /swapfile, swapon /swapfile (verify with free -h / swapon --show). Persistent: add to /etc/fstab: /swapfile none swap sw 0 0. An LVM swap LV would be mkswap /dev/vg/swaplv. Adjust swappiness at runtime with sysctl vm.swappiness=<n> (persist in /etc/sysctl.d/).",
   e:"swapon -a activates all fstab swap entries on boot. Swap-on-file with fallocate is quick; permissions 600 are required for security."},
  {t:"Shell & Text Processing", q:"What is the difference between find and locate, and how do you process text with awk/sed/grep?",
   a:"find searches the filesystem in real time (find /var -name '*.log' -mtime +7 -size +100M), while locate uses a prebuilt database (updatedb/mlocate) and is fast but stale. grep filters lines (grep -rn 'Error' /var/log); sed edits streams (sed -i 's/old/new/g' file); awk is a field-processing language (awk '{print $1}' /etc/passwd; awk -F: '$3>=1000{print $1}' /etc/passwd).",
   e:"find can act on results with -exec; grep -v inverts, -E enables extended regex; awk is column-oriented ($1, $NF, -F separator) and sed is substitution/editing — together they are the core text-processing trio."},
  {t:"Virtualization", q:"How does RHEL 10 provide KVM virtualization and what tools manage VMs?",
   a:"KVM turns the kernel into a hypervisor (kvm_intel/kvm_amd modules); libvirt manages guests. Install the virtualization host group (dnf groupinstall 'Virtualization Host') or libvirt/qemu-kvm. virsh manages VMs (virsh list --all, start/shutdown/dumpxml); virt-manager provides a GUI; VMs can be defined with cloud-init and Kickstart.",
   e:"virt-host-validate verifies hardware virtualization (VT-x/AMD-V) and libvirt readiness. libvirtd (monolithic in newer RHEL) plus qemu-kvm is the supported RHEL virtualization stack."},
  {t:"Networking", q:"How do you mount an NFS share persistently on a RHEL 10 client?",
   a:"Install nfs-utils; discover exports with showmount -e server; create a mount point; add an fstab line: server:/export /mnt nfs defaults,_netdev,x-systemd.automount 0 0 (or use the autofs service), then mount /mnt. Verify with mount | grep nfs and df -h. firewall-cmd must allow nfs on the client/server as needed.",
   e:"_netdev (and x-systemd.automount) makes systemd wait for networking before mounting and can auto-mount on demand. RHEL 10 supports NFSv4.x; autofs is the alternative for dynamic mounts."}
];
